object Versions {
    const val kotlin = "1.7.10"
    const val desugar = "1.1.5"
    const val gradleBuildTools = "7.2.2"
    const val coreKtx = "1.8.0"
    const val appcompat = "1.5.0"
    const val fragment = "1.5.2"
    const val constraintLayout = "2.1.4"
    const val compose = "1.2.1"
    const val composeCompiler = "1.3.0"
    const val activityCompose = "1.5.1"
    const val coilCompose = "2.1.0"
    const val constraintLayoutCompose = "1.0.1"
    const val material = "1.6.1"
    const val lifecycle = "2.5.1"
    const val preference = "1.2.0"
    const val timber = "5.0.1"
    const val coroutinesTest = "1.6.4"
    const val mockk = "1.12.5"
    const val workRuntime = "2.7.0"
    const val junit = "4.13.2"
    const val benManesVersions = "0.42.0"
    const val koin = "3.2.0"
    const val navigation = "2.5.1"
}